[build]
  base = "frontend/cityplus"
  publish = "frontend/cityplusbuild"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200